# -*- coding: utf-8 -*-
"""multi_agent_ai_fraud_detection (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17w04oKXGCVPhYKK9ttA9UUojNnnUJmxK

#                         GenAI Pioneer Labs
# Multi-Agent AI Fraud Detection System using LangGraph

This notebook demonstrates how to build a **Multi-Agent AI Fraud Detection Pipeline** using:

- LangChain
- LangGraph
- Groq LLM
- Rule-Based Detection
- ML-Based Fraud Scoring
- Graph-Based Workflow Orchestration
- Multi-Agent Reasoning

## Agents Included

1. Transaction Monitoring Agent  
2. Risk Scoring Agent  
3. Rule-Based Fraud Agent  
4. Machine Learning Fraud Agent  
5. Geo-Risk Agent  
6. Device Intelligence Agent  
7. Behavioral Analysis Agent  
8. LLM Decision Agent  
9. SAR (Suspicious Activity Report) Generator Agent  

---

Designed for:
- Banking AI
- AML Systems
- Fraud Detection
- Risk Intelligence
- Financial Crime Monitoring
- Agentic AI Systems

## Install Dependencies
Run this cell if packages are not installed.
"""

# This cell is responsible for installing all necessary Python libraries for the multi-agent fraud detection system.
# Each library plays a specific role in building, running, or analyzing the system.

# !pip install: This is a shell command executed within the Jupyter/Colab environment.
# It uses 'pip', the Python package installer, to download and install packages from PyPI (Python Package Index).

# -q: This flag stands for 'quiet'. When used, pip will install the packages without displaying verbose output,
# making the installation process less cluttered in the notebook.

# Libraries being installed:
# 1.  langchain: A framework for developing applications powered by large language models. It provides tools for chaining LLM calls,
#     working with prompts, and integrating with various data sources and other tools.
# 2.  langgraph: An extension of LangChain, specifically designed for building stateful, multi-actor applications with LLMs.
#     In this fraud detection system, LangGraph is crucial for orchestrating the flow between different agents (e.g., Transaction Monitoring,
#     Risk Scoring, LLM Decision Agent). It allows defining a graph of nodes (agents) and edges (transitions between agents),
#     enabling complex decision-making processes and sequential or conditional agent execution.
#     It manages the state that is passed between agents, ensuring that each agent has access to the latest information.
# 3.  langchain-groq: This is a LangChain integration for Groq, providing a specific connector to use Groq's fast LLMs within the LangChain framework.
#     Groq LLMs are used here for rapid processing and decision-making by the LLM Decision Agent.
# 4.  pandas: A powerful data manipulation and analysis library. It's used for handling tabular data structures (DataFrames),
#     which are essential for processing transaction details and potentially for data preparation or aggregation tasks.
# 5.  scikit-learn: A comprehensive machine learning library. It's used for implementing machine learning models, such as the
#     ML-Based Fraud Scoring agent, which might involve classification algorithms.
# 6.  networkx: A Python library for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
#     While not explicitly used in the provided agent functions, it could be utilized for visualizing the LangGraph workflow
#     or for more advanced graph-based analysis of transactions or relationships.
# 7.  matplotlib: A widely used plotting library for Python. It's typically used for creating static, interactive, and animated
#     visualizations in Python, which could be useful for visualizing data distributions, fraud patterns, or agent interactions.
!pip install langchain langgraph langchain-groq pandas scikit-learn networkx matplotlib -q

"""## Import Libraries"""

# Import necessary libraries and modules.
# These imports provide the building blocks for defining the transaction state, implementing agents, and constructing the LangGraph workflow.

from typing import Dict, Any, TypedDict # Essential for type hinting dictionaries and defining TransactionState

# typing: Dict, Any, TypedDict
#   - Dict: Used for type hinting dictionaries, indicating that a variable is expected to be a dictionary.
#   - Any: A special type from 'typing' that indicates an unconstrained type. Used when the type can be anything.
#   - TypedDict: (from typing) Used to create dictionary types with a fixed set of keys and their corresponding value types.
#                This provides static type checking for dictionaries, making the code more robust and readable.
#                It is crucial for defining our 'TransactionState' with clear structure.
import random
# random: Used here to simulate random values for risk scores and ML fraud probabilities,
#         as we are not connecting to actual ML models or external services in this demonstration.
import pandas as pd
# pandas: A powerful data manipulation and analysis library. While not directly used in the agent logic within this specific
#         demo beyond state management, it's a fundamental library for data-centric AI applications, especially when
#         dealing with structured transaction data or preparing datasets for ML models.
import numpy as np
# numpy: The fundamental package for numerical computing in Python. Similar to pandas, it's a core library for data science.
#        Though not directly called in the current agent implementations, it's often an underlying dependency for libraries
#        like pandas and scikit-learn, and essential for any numerical operations or array manipulations.

from langgraph.graph import StateGraph
# langgraph.graph.StateGraph: The core component of LangGraph. It allows defining a stateful graph where nodes are agents
#                             (or functions) and edges define the transitions between these agents. It manages the shared
#                             state that is passed and updated by each agent in the workflow.
from langchain_groq import ChatGroq
# langchain_groq.ChatGroq: This module provides an interface to integrate Groq's fast large language models (LLMs) with LangChain.
#                          It allows the LLM Decision Agent to use Groq for rapid decision-making based on the gathered risk factors.

from typing import Dict, Any, TypedDict

# Define the shared state structure for the multi-agent system using TypedDict.
# This 'TransactionState' acts as the central data store that is passed between and updated by different agents
# in the fraud detection pipeline. It ensures all agents operate on a consistent and well-defined set of information.

class TransactionState(TypedDict):
    # transaction: Dict[str, Any]
    #   - Stores the details of the transaction being analyzed. It's a dictionary where keys are strings (e.g., 'amount', 'location')
    #     and values can be of any type (e.g., integer, string).
    transaction: Dict[str, Any]

    # risk_score: int
    #   - An integer representing a numerical assessment of the transaction's risk. Typically ranges from 0 to 100.
    #     Updated by the Risk Scoring Agent.
    risk_score: int

    # rule_based_flag: bool
    #   - A boolean flag indicating whether the transaction triggered any predefined rule-based fraud conditions (e.g., amount too high).
    #     True if a rule is triggered, False otherwise. Updated by the Rule-Based Fraud Agent.
    rule_based_flag: bool

    # ml_fraud_probability: float
    #   - A floating-point number representing the probability of fraud as predicted by a Machine Learning model.
    #     Typically ranges from 0.0 to 1.0. Updated by the ML Fraud Agent.
    ml_fraud_probability: float

    # geo_risk: str
    #   - A string indicating the geographical risk level (e.g., 'Low', 'High') associated with the transaction's location.
    #     Updated by the Geo-Risk Agent.
    geo_risk: str

    # device_risk: str
    #   - A string indicating the risk level associated with the device used for the transaction (e.g., 'Low', 'High').
    #     Updated by the Device Intelligence Agent.
    device_risk: str

    # behavior_risk: str
    #   - A string indicating the risk level based on the customer's behavioral patterns (e.g., 'Low', 'High').
    #     Updated by the Behavioral Analysis Agent.
    behavior_risk: str

    # final_decision: str
    #   - The ultimate decision regarding the transaction (e.g., 'APPROVE', 'REVIEW', 'DECLINE').
    #     Determined and updated by the LLM Decision Agent.
    final_decision: str

    # sar_report: str
    #   - A string containing a Suspicious Activity Report, generated if the transaction is deemed suspicious.
    #     Generated and updated by the SAR Agent.
    sar_report: str

if 'TransactionState' in globals():
    print('TransactionState is successfully defined.')
else:
    print('TransactionState is NOT defined. Please ensure the cell defining it has been executed.')

"""
## Initialize Groq LLM

Replace with your actual API key.
"""

import os
from dotenv import load_dotenv
load_dotenv()

# Initialize the Groq Large Language Model (LLM) for decision-making.
# This cell sets up the connection to Groq's API and configures the LLM for use in our agents.

# GROQ_API_KEY: This variable holds your personal API key for accessing the Groq API.
# It is loaded from environment variables (e.g. from the .env file) to prevent exposing secrets.
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")

llm = ChatGroq(
    temperature=0.3,
    groq_api_key=GROQ_API_KEY,
    model_name="llama-3.3-70b-versatile"
)
#   - ChatGroq is a class from `langchain_groq` that facilitates interaction with Groq's chat models.
#   - temperature=0.3: This parameter controls the randomness of the LLM's output.
#     A lower temperature (closer to 0) makes the output more deterministic and focused,
#     which is generally preferred for tasks like fraud detection where consistent and factual responses are critical.
#     A higher temperature (closer to 1) leads to more creative and diverse outputs.
#   - groq_api_key=GROQ_API_KEY: Passes the API key required for authentication with the Groq service.
#   - model_name="llama-3.3-70b-versatile": Specifies which Groq model to use. Different models have varying
#     capabilities and performance characteristics. 'llama-3.3-70b-versatile' is a powerful model suitable for complex reasoning.

"""## Define Transaction State"""

from typing import Dict, Any, TypedDict

# Define the shared state structure for the multi-agent system using TypedDict.
# This 'TransactionState' acts as the central data store that is passed between and updated by different agents
# in the fraud detection pipeline. It ensures all agents operate on a consistent and well-defined set of information.

class TransactionState(TypedDict):
    # transaction: Dict[str, Any]
    #   - Stores the details of the transaction being analyzed. It's a dictionary where keys are strings (e.g., 'amount', 'location')
    #     and values can be of any type (e.g., integer, string).
    transaction: Dict[str, Any]

    # risk_score: int
    #   - An integer representing a numerical assessment of the transaction's risk. Typically ranges from 0 to 100.
    #     Updated by the Risk Scoring Agent.
    risk_score: int

    # rule_based_flag: bool
    #   - A boolean flag indicating whether the transaction triggered any predefined rule-based fraud conditions (e.g., amount too high).
    #     True if a rule is triggered, False otherwise. Updated by the Rule-Based Fraud Agent.
    rule_based_flag: bool

    # ml_fraud_probability: float
    #   - A floating-point number representing the probability of fraud as predicted by a Machine Learning model.
    #     Typically ranges from 0.0 to 1.0. Updated by the ML Fraud Agent.
    ml_fraud_probability: float

    # geo_risk: str
    #   - A string indicating the geographical risk level (e.g., 'Low', 'High') associated with the transaction's location.
    #     Updated by the Geo-Risk Agent.
    geo_risk: str

    # device_risk: str
    #   - A string indicating the risk level associated with the device used for the transaction (e.g., 'Low', 'High').
    #     Updated by the Device Intelligence Agent.
    device_risk: str

    # behavior_risk: str
    #   - A string indicating the risk level based on the customer's behavioral patterns (e.g., 'Low', 'High').
    #     Updated by the Behavioral Analysis Agent.
    behavior_risk: str

    # New fields for expanded agents:
    # aml_pattern_detected: str
    #   - A string indicating if any AML patterns were detected (e.g., 'None', 'Structuring', 'Layering').
    aml_pattern_detected: str

    # behavioral_biometrics_risk: str
    #   - A string indicating the risk from advanced behavioral biometrics (e.g., 'Low', 'Anomalous', 'Suspicious').
    behavioral_biometrics_risk: str

    # geo_velocity_risk: str
    #   - A string indicating the risk from geo-velocity analysis (e.g., 'Low', 'High-Velocity').
    geo_velocity_risk: str

    # synthetic_identity_flag: bool
    #   - A boolean flag if synthetic identity indicators are found.
    synthetic_identity_flag: bool

    # account_takeover_risk: str
    #   - A string indicating risk of account takeover (e.g., 'Low', 'ATO-Detected').
    account_takeover_risk: str

    # final_decision: str
    #   - The ultimate decision regarding the transaction (e.g., 'APPROVE', 'REVIEW', 'DECLINE').
    #     Determined and updated by the LLM Decision Agent.
    final_decision: str

    # sar_report: str
    #   - A string containing a Suspicious Activity Report, generated if the transaction is deemed suspicious.
    #     Generated and updated by the SAR Agent.
    sar_report: str

from typing import Dict, Any # Added for Dict and Any type hints

# Helper function to create an initial TransactionState object.
# This function sets up a new transaction with default values for all risk factors and decisions,
# before any agents have processed it.

def create_initial_state(transaction: Dict[str, Any]) -> TransactionState:
    # transaction: Dict[str, Any]
    #   - The raw transaction data provided by the user or system, which will be the starting point for analysis.
    #   - This dictionary contains details like 'amount', 'location', 'device_id', 'hour', 'customer_id'.
    return {
        "transaction": transaction,            # Store the original transaction details.
        "risk_score": 0,                       # Initialize risk score to 0.
        "rule_based_flag": False,              # Initialize rule-based flag to False (no rules triggered yet).
        "ml_fraud_probability": 0.0,           # Initialize ML probability to 0.0.
        "geo_risk": "Unknown",                 # Initialize geo-risk to 'Unknown'.
        "device_risk": "Unknown",              # Initialize device-risk to 'Unknown'.
        "behavior_risk": "Unknown",            # Initialize behavior-risk to 'Unknown'.
        "aml_pattern_detected": "None",      # Initialize AML pattern detection to 'None'.
        "behavioral_biometrics_risk": "Low", # Initialize behavioral biometrics risk to 'Low'.
        "geo_velocity_risk": "Low",          # Initialize geo-velocity risk to 'Low'.
        "synthetic_identity_flag": False,    # Initialize synthetic identity flag to False.
        "account_takeover_risk": "Low",      # Initialize account takeover risk to 'Low'.
        "final_decision": "Pending",           # Initialize final decision to 'Pending' as it hasn't been made yet.
        "sar_report": ""                       # Initialize SAR report as an empty string.
    }

"""# Fraud Detection Agents

## Transaction Monitoring Agent
"""

# Agent 1: Transaction Monitoring Agent
# This agent acts as the entry point to the fraud detection pipeline. Its primary role is to log the incoming
# transaction and pass it along to the next agents in the workflow.

def transaction_monitoring_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state of the transaction. This agent receives the initial state.
    print("\n[Monitoring Agent]")
    print("Incoming Transaction:", state["transaction"])
    # It prints the transaction details for monitoring purposes.
    # In a real-world scenario, this agent might also perform initial data validation,
    # enrichment (e.g., fetching customer historical data), or logging to an audit system.
    return state
    # The agent returns the (unchanged) state, passing the transaction details to the next agent.

"""## Risk Scoring Agent"""

# Agent 2: Risk Scoring Agent
# This agent is responsible for generating an overall numerical risk score for the transaction.
# In this demonstration, the score is simulated using a random number.

def risk_scoring_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state of the transaction, which includes the transaction details.
    print("\n[Risk Scoring Agent]")
    # state["risk_score"] = random.randint(1, 100):
    #   - This line simulates a risk score by assigning a random integer between 1 and 100.
    #   - In a real system, this would typically involve complex algorithms, historical data analysis,
    #     or even inputs from other specialized risk models to calculate a sophisticated risk score.
    state["risk_score"] = random.randint(1, 100)
    print("Risk Score:", state["risk_score"])
    return state
    # The updated state, now containing the calculated risk score, is returned for subsequent agents.

"""## Rule-Based Fraud Agent"""

# Agent 3: Rule-Based Fraud Agent
# This agent applies predefined business rules to identify potentially fraudulent transactions.
# It flags a transaction if it meets specific, hard-coded criteria.

def rule_based_detection_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state, including the transaction details and potentially the risk score.
    print("\n[Rule-Based Agent]")

    # amount = state["transaction"]["amount"]:
    #   - Extracts the transaction amount from the shared state.
    amount = state["transaction"]["amount"]

    # if amount > 1000:
    #   - This is a simple rule: if the transaction amount exceeds 1000 units, it's considered suspicious.
    #   - In a real system, there would be many such rules, potentially managed in a dedicated rule engine,
    #     checking for various patterns like transaction velocity, unusual geographies, large transfers,
    #     or transactions to blacklisted accounts.
    if amount > 1000:
        state["rule_based_flag"] = True # Set the flag to True if the rule is triggered.

    print("Rule Based Fraud Flag:", state["rule_based_flag"])
    return state
    # The updated state, reflecting whether a rule was triggered, is returned.

"""## ML Fraud Agent"""

# Agent 4: Machine Learning Fraud Agent
# This agent simulates the output of a Machine Learning model designed to predict the probability of fraud.
# In this demonstration, a random probability is generated.

def machine_learning_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state.
    print("\n[ML Fraud Agent]")

    # probability = random.uniform(0, 1):
    #   - Generates a random floating-point number between 0.0 and 1.0, simulating the output of an ML model.
    #   - In a real system, this agent would integrate with a deployed ML model (e.g., a classification model trained
    #     on historical fraud data). The model would take transaction features as input and output a fraud probability score.
    probability = random.uniform(0, 1)

    # state["ml_fraud_probability"] = probability:
    #   - Updates the shared state with the simulated fraud probability.
    state["ml_fraud_probability"] = probability

    print("Fraud Probability:", round(probability, 2))
    return state
    # The updated state, including the ML fraud probability, is returned.

"""## Geo Risk Agent"""

# Agent 5: Geo-Risk Agent
# This agent assesses the risk associated with the geographical location of the transaction.
# It flags locations that are known for higher fraud rates or are on a watchlist.

def geo_risk_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state.
    print("\n[Geo Risk Agent]")

    # risky_locations = [...]:
    #   - A list of locations considered high-risk. This could be based on sanctions lists, historical fraud data,
    #     or geographical risk intelligence databases.
    risky_locations = ["Russia", "Nigeria", "Unknown"]

    # location = state["transaction"]["location"]:
    #   - Extracts the transaction location from the shared state.
    location = state["transaction"]["location"]

    # if location in risky_locations: ... else: ...:
    #   - Checks if the transaction's location is present in the list of high-risk locations.
    #   - Updates the 'geo_risk' field in the state accordingly.
    if location in risky_locations:
        state["geo_risk"] = "High"
    else:
        state["geo_risk"] = "Low"

    print("Geo Risk:", state["geo_risk"])

    return state
    # The updated state, with the assessed geographical risk, is returned.

"""## Device Intelligence Agent"""

# Agent 6: Device Intelligence Agent
# This agent evaluates the risk associated with the device used to initiate the transaction.
# It identifies potentially suspicious devices or usage patterns.

def device_intelligence_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state.
    print("\n[Device Intelligence Agent]")

    # suspicious_devices = [...]:
    #   - A list of device identifiers or types known to be associated with fraudulent activities.
    #   - This could include devices identified as using VPNs, Tor browsers, emulators, or devices on a blacklist.
    risky_devices = ["TOR_BROWSER", "VPN_DEVICE", "EMULATOR"]

    # device = state["transaction"]["device_id"]:
    #   - Extracts the device ID from the transaction details in the shared state.
    device = state["transaction"]["device_id"]

    # if device in risky_devices: ... else: ...:
    #   - Checks if the transaction's device ID matches any in the list of suspicious devices.
    #   - Updates the 'device_risk' field in the state accordingly.
    if device in risky_devices:
        state["device_risk"] = "High"
    else:
        state["device_risk"] = "Low"

    print("Device Risk:", state["device_risk"])

    return state
    # The updated state, with the assessed device risk, is returned.

"""## Behavior Analysis Agent"""

# Agent 7: Behavior Analysis Agent
# This agent analyzes the transaction based on the time of day, comparing it against typical user behavior
# or known patterns of fraudulent activity.

def behavior_analysis_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state.
    print("\n[Behavior Analysis Agent]")

    # abnormal_hours = [...]:
    #   - A list of hours considered abnormal for transactions, often indicating late-night activity
    #     which can be a red flag for fraud.
    #   - In a more sophisticated system, this would involve comparing against a user's typical transaction hours.
    abnormal_hours = [1, 2, 3, 4] # e.g., 1 AM, 2 AM, 3 AM, 4 AM

    # hour = state["transaction"]["hour"]:
    #   - Extracts the hour of the transaction from the shared state.
    hour = state["transaction"]["hour"]

    # if hour in abnormal_hours: ... else: ...:
    #   - Checks if the transaction's hour falls within the defined abnormal hours.
    #   - Updates the 'behavior_risk' field in the state accordingly.
    if hour in abnormal_hours:
        state["behavior_risk"] = "High"
    else:
        state["behavior_risk"] = "Low"

    print("Behavior Risk:", state["behavior_risk"])

    return state
    # The updated state, with the assessed behavioral risk, is returned.

"""## AML Pattern Agent"""

# Agent 8 (New): AML (Anti-Money Laundering) Pattern Agent
# This agent identifies potential money laundering patterns based on transaction characteristics.

def aml_pattern_agent(state: TransactionState) -> TransactionState:
    print("\n[AML Pattern Agent]")

    transaction = state["transaction"]
    amount = transaction["amount"]
    location = transaction["location"]

    # Simulate basic AML patterns
    if amount > 5000 and location in ["Russia", "Nigeria"]:
        state["aml_pattern_detected"] = "High-Risk Location & Large Amount"
    elif amount > 10000:
        state["aml_pattern_detected"] = "Unusually Large Transaction"
    else:
        state["aml_pattern_detected"] = "None"

    print("AML Pattern Detected:", state["aml_pattern_detected"])
    return state

"""## Behavioral Biometrics Agent"""

# Agent 9 (New): Behavioral Biometrics Agent
# This agent assesses risk based on simulated user behavioral biometrics, like unusual login patterns.

def behavioral_biometrics_agent(state: TransactionState) -> TransactionState:
    print("\n[Behavioral Biometrics Agent]")

    # Simulate behavioral biometrics risk
    # In a real scenario, this would involve analyzing user input dynamics, login location variance, etc.
    risk_level = random.choice(["Low", "Anomalous", "Suspicious"])
    state["behavioral_biometrics_risk"] = risk_level

    print("Behavioral Biometrics Risk:", state["behavioral_biometrics_risk"])
    return state

"""## Geo-Velocity Agent"""

# Agent 10 (New): Geo-Velocity Agent
# This agent detects rapid changes in transaction locations, which can indicate fraud.

def geo_velocity_agent(state: TransactionState) -> TransactionState:
    print("\n[Geo-Velocity Agent]")

    transaction = state["transaction"]
    current_location = transaction["location"]

    # Simulate geo-velocity risk: if location changes drastically in a short time (e.g., from NY to Russia in 1 hour)
    # For this simulation, we'll use a simple rule.
    if current_location == "Russia" and transaction["hour"] < 5: # Assuming a previous transaction was recent and in a distant location
        state["geo_velocity_risk"] = "High-Velocity Anomaly"
    elif current_location == "London" and transaction["hour"] < 8:
        state["geo_velocity_risk"] = "Moderate-Velocity Anomaly"
    else:
        state["geo_velocity_risk"] = "Low"

    print("Geo-Velocity Risk:", state["geo_velocity_risk"])
    return state

"""## Synthetic Identity Agent"""

# Agent 11 (New): Synthetic Identity Agent
# This agent looks for indicators of synthetic identities (fraudulent identities created from real and fake data).

def synthetic_identity_agent(state: TransactionState) -> TransactionState:
    print("\n[Synthetic Identity Agent]")

    transaction = state["transaction"]
    customer_id = transaction["customer_id"]

    # Simulate synthetic identity detection
    # In a real system, this would involve cross-referencing with identity databases, checking data consistency, etc.
    if customer_id == "CUST_1005" or customer_id == "CUST_XYZ_SYNTHETIC": # Example: CUST_1005 from sample_transactions
        state["synthetic_identity_flag"] = True
    else:
        state["synthetic_identity_flag"] = False

    print("Synthetic Identity Flag:", state["synthetic_identity_flag"])
    return state

"""## Account Takeover Agent"""

# Agent 12 (New): Account Takeover (ATO) Agent
# This agent detects suspicious activities that might indicate an account takeover attempt.

def account_takeover_agent(state: TransactionState) -> TransactionState:
    print("\n[Account Takeover Agent]")

    transaction = state["transaction"]
    device_id = transaction["device_id"]
    hour = transaction["hour"]

    # Simulate ATO detection
    # This would typically involve comparing current behavior to historical user profiles (e.g., login location, device, time).
    if device_id == "VPN_DEVICE" and hour < 5: # Suspicious device + abnormal hour
        state["account_takeover_risk"] = "ATO-Detected (High)"
    elif device_id == "WEB_BROWSER_ABC" and hour < 8: # Another suspicious combination
        state["account_takeover_risk"] = "ATO-Suspected (Medium)"
    else:
        state["account_takeover_risk"] = "Low"

    print("Account Takeover Risk:", state["account_takeover_risk"])
    return state

"""## LLM Decision Agent"""

# Agent 8: LLM Decision Agent
# This is a critical agent that synthesizes all the information gathered by previous agents.
# It uses a Large Language Model (LLM) to make a final, nuanced decision (APPROVE, REVIEW, DECLINE)
# and provides an explanation for that decision.

def llm_decision_agent(state: TransactionState) -> TransactionState:

    # state: TransactionState
    #   - The current shared state, which now contains all risk assessments from previous agents.
    print("\n[LLM Decision Agent]")

    # prompt: This f-string dynamically constructs a detailed prompt for the LLM.
    # It includes:
    #   - A clear role for the AI ("banking fraud investigation AI").
    #   - All collected transaction details and risk factors (amount, location, device_id, hour, risk_score,
    #     rule_based_flag, ml_fraud_probability, geo_risk, device_risk, behavior_risk).
    #   - Explicit instructions for the desired output format (DECIDE: APPROVE/REVIEW/DECLINE and WHY).
    prompt = f'''
    You are a banking fraud investigation AI.

    Analyze this transaction:

    Transaction: {state["transaction"]}

    Risk Score: {state["risk_score"]}
    Rule Flag: {state["rule_based_flag"]}
    ML Fraud Probability: {state["ml_fraud_probability"]}
    Geo Risk: {state["geo_risk"]}
    Device Risk: {state["device_risk"]}
    Behavior Risk: {state["behavior_risk"]}

    # New Agent Information:
    AML Pattern Detected: {state["aml_pattern_detected"]}
    Behavioral Biometrics Risk: {state["behavioral_biometrics_risk"]}
    Geo-Velocity Risk: {state["geo_velocity_risk"]}
    Synthetic Identity Flag: {state["synthetic_identity_flag"]}
    Account Takeover Risk: {state["account_takeover_risk"]}

    Decide:
    APPROVE
    REVIEW
    DECLINE

    Also explain WHY.
    '''

    # response = llm.invoke(prompt):
    #   - Sends the constructed prompt to the initialized Groq LLM (llm object from earlier).
    #   - The LLM processes the information and generates a response based on its training and the prompt instructions.
    response = llm.invoke(prompt)

    # state["final_decision"] = response.content:
    #   - Extracts the LLM's generated content (the decision and explanation) and updates the 'final_decision'
    #     field in the shared state.
    state["final_decision"] = response.content

    print(response.content)

    return state
    # The updated state, including the LLM's final decision and rationale, is returned.

"""## SAR Report Agent"""

# Agent 9: SAR (Suspicious Activity Report) Agent
# This agent generates a structured Suspicious Activity Report if the transaction warrants it.
# The report summarizes key findings and decisions for compliance and further investigation.

def sar_agent(state: TransactionState) -> TransactionState:

    # state: TransactionState
    #   - The current shared state, including all risk factors and the final decision from the LLM.
    print("\n[SAR Agent]")

    # sar_report: This f-string constructs the SAR report based on the aggregated information in the state.
    # It includes:
    #   - Transaction details.
    #   - Overall risk score.
    #   - ML fraud probability.
    #   - The final decision and its explanation from the LLM.
    sar_report = f'''
    Suspicious Activity Report

    Transaction Details:
    {state["transaction"]}

    Risk Score:
    {state["risk_score"]}

    ML Fraud Probability:
    {round(state["ml_fraud_probability"],2)}

    Final Decision:
    {state["final_decision"]}
    '''

    # state["sar_report"] = sar_report:
    #   - Updates the 'sar_report' field in the shared state with the generated report string.
    state["sar_report"] = sar_report

    print(sar_report)

    return state
    # The updated state, now containing the SAR report, is returned. This marks the end of the pipeline's processing for this transaction.

"""# Build LangGraph Workflow"""

# Build the LangGraph Workflow
# This section defines the structure and flow of our multi-agent fraud detection pipeline.
# LangGraph allows us to define nodes (agents) and edges (transitions) to create a directed graph,
# ensuring state is passed correctly between agents.

# graph = StateGraph(TransactionState):
#   - Initializes a new StateGraph instance. The 'TransactionState' (our TypedDict) is passed to it,
#     informing LangGraph about the structure of the shared state that will be managed throughout the graph's execution.
graph = StateGraph(TransactionState)

# graph.add_node("name", agent_function):
#   - Adds each of our defined agents as a 'node' in the graph.
#   - The first argument is a unique string identifier for the node (e.g., "monitor").
#   - The second argument is the Python function (our agent) that will be executed when this node is active.
graph.add_node("monitor", transaction_monitoring_agent)
graph.add_node("risk_score", risk_scoring_agent)
graph.add_node("rule_based", rule_based_detection_agent)
graph.add_node("ml_agent", machine_learning_agent)
graph.add_node("geo_agent", geo_risk_agent)
graph.add_node("device_agent", device_intelligence_agent)
graph.add_node("behavior_agent", behavior_analysis_agent)

# Adding new agents
graph.add_node("aml_pattern", aml_pattern_agent)
graph.add_node("behavioral_biometrics", behavioral_biometrics_agent)
graph.add_node("geo_velocity", geo_velocity_agent)
graph.add_node("synthetic_identity", synthetic_identity_agent)
graph.add_node("account_takeover", account_takeover_agent)

graph.add_node("llm_decision", llm_decision_agent)
graph.add_node("sar_agent", sar_agent)

# graph.set_entry_point("monitor"):
#   - Specifies the starting node for the graph execution. All transactions will begin their journey at the 'monitor' agent.
graph.set_entry_point("monitor")

# graph.add_edge("source_node", "target_node"):
#   - Defines a directed transition (an 'edge') from a 'source_node' to a 'target_node'.
#   - When the 'source_node' finishes execution, control (and the updated state) is passed to the 'target_node'.
#   - This establishes the sequential flow of our fraud detection pipeline.
graph.add_edge("monitor", "risk_score")
graph.add_edge("risk_score", "rule_based")
graph.add_edge("rule_based", "ml_agent")
graph.add_edge("ml_agent", "geo_agent")
graph.add_edge("geo_agent", "device_agent")
graph.add_edge("device_agent", "behavior_agent")

# Connecting new agents sequentially before the LLM decision agent
graph.add_edge("behavior_agent", "aml_pattern")
graph.add_edge("aml_pattern", "behavioral_biometrics")
graph.add_edge("behavioral_biometrics", "geo_velocity")
graph.add_edge("geo_velocity", "synthetic_identity")
graph.add_edge("synthetic_identity", "account_takeover")
graph.add_edge("account_takeover", "llm_decision")

graph.add_edge("llm_decision", "sar_agent")

# fraud_pipeline = graph.compile():
#   - Compiles the defined graph into an executable Runnable object.
#   - This step optimizes the graph for execution and makes it ready to be invoked with an initial state.
#   - The 'fraud_pipeline' object is what we will call to run a transaction through the entire agent workflow.
fraud_pipeline = graph.compile()

"""# Visualize Workflow"""

# Visualize the LangGraph Workflow
# This cell generates and displays a visual representation of the agent workflow using Mermaid syntax.
# It helps in understanding the flow of control and state transitions between different agents.

# from IPython.display import Image, display:
#   - Image: Used to display image data (like PNGs) within the Jupyter/Colab notebook output.
#   - display: A function to render various Python objects in a rich format in the notebook.
from IPython.display import Image, display

# from langchain_core.runnables.graph import MermaidDrawMethod:
#   - MermaidDrawMethod: Specifies the method to use for drawing the graph, in this case, using an API to render Mermaid code.
from langchain_core.runnables.graph import MermaidDrawMethod

# display(Image(fraud_pipeline.get_graph().draw_mermaid_png(draw_method=MermaidDrawMethod.API))):
#   - fraud_pipeline.get_graph(): Retrieves the underlying graph object from the compiled pipeline.
#   - .draw_mermaid_png(draw_method=MermaidDrawMethod.API): Converts the graph structure into a Mermaid diagram
#     and renders it as a PNG image using an external API for the conversion.
#   - Image(...): Wraps the PNG data so it can be displayed by IPython.
#   - display(...): Renders the image in the notebook output.
# This visualization is invaluable for debugging, documentation, and explaining the system's architecture.
display(
    Image(
        fraud_pipeline.get_graph().draw_mermaid_png(
            draw_method=MermaidDrawMethod.API
        )
    )
)

"""# Test Transaction"""

# Test a Sample Transaction through the Fraud Detection Pipeline
# This cell defines a sample transaction and then runs it through the entire LangGraph workflow,
# demonstrating how the agents process the transaction and update the state.

# transaction: Dict defining a sample transaction.
#   - amount: The monetary value of the transaction.
#   - location: The geographical location where the transaction occurred.
#   - device_id: Identifier for the device used (e.g., 'VPN_DEVICE' for a VPN-enabled device).
#   - hour: The hour of the day when the transaction took place (24-hour format).
#   - customer_id: Unique identifier for the customer.
transaction = {
    "amount": 2500,
    "location": "Nigeria",
    "device_id": "VPN_DEVICE",
    "hour": 2,
    "customer_id": "CUST_1001"
}

# state = create_initial_state(transaction):
#   - Calls the helper function to create an initial TransactionState object,
#     populating it with the sample transaction data and default values for other fields.
state = create_initial_state(transaction)

# final_state = fraud_pipeline.invoke(state):
#   - This is the core execution step. The 'invoke' method of the compiled LangGraph pipeline
#     takes the initial state and runs it through all the defined agents in sequence.
#   - Each agent receives the current state, processes it, updates relevant fields, and passes
#     the modified state to the next agent according to the graph's edges.
#   - The 'final_state' will contain all the accumulated information and decisions made by the agents.
final_state = fraud_pipeline.invoke(state)

"""# Display Final Results"""

# Display the Final Results of the Fraud Detection Pipeline
# This cell prints the ultimate decision made by the LLM Decision Agent and the generated
# Suspicious Activity Report (SAR) after the entire pipeline has processed the transaction.

print("\n=========== FINAL RESULTS ===========")

print("\nDecision:")
# print(final_state["final_decision"]):
#   - Accesses and prints the 'final_decision' field from the 'final_state' dictionary.
#   - This typically contains the LLM's APPROVE/REVIEW/DECLINE decision along with its explanation.
print(final_state["final_decision"])

print("\nSAR Report:")
# print(final_state["sar_report"]):
#   - Accesses and prints the 'sar_report' field from the 'final_state' dictionary.
#   - This contains the structured report generated by the SAR Agent, summarizing key transaction
#     details and risk factors that led to the final decision.
print(final_state["sar_report"])

"""# Advanced Extensions

GenAI Pioneer has enhanced this system with many advanced features,some of which are

- Neo4j Graph Fraud Detection
- Real-time Kafka Streaming
- Multi-Agent Investigation Loops
- Human-in-the-loop Review
- AML Pattern Detection
- KYC Risk Engines
- Behavioral Biometrics
- Agentic SAR Automation
- RAG-based Financial Investigation
- Pega AI Workflow Integration
- Multi-bank Fraud Intelligence Sharing

# Kafka Integration into the Code
Integrate Kafka into the multi-agent fraud detection system. This involves installing Kafka libraries, setting up a Kafka producer to simulate streaming transaction data, modifying the `transaction_monitoring_agent` to consume transactions from a Kafka topic, and updating the fraud detection pipeline's execution to process these incoming streamed transactions in real-time.

## Install Kafka Libraries

### Subtask:
Install the necessary Python libraries for Kafka integration, such as `confluent-kafka` or `kafka-python`.

**Reasoning**:
The subtask requires installing the `confluent-kafka` library. I will use a `pip install` command in a new code cell to install it.
"""

pip install confluent-kafka -q

"""**Reasoning**:
Now that the Kafka library is installed, the next step is to set up a Kafka producer to simulate streaming transaction data. This requires importing the Producer class, configuring the Kafka broker, and defining a function to produce messages.


"""

import json
from confluent_kafka import Producer
import time

# Kafka broker configuration
KAFKA_BROKER = 'localhost:9092' # Replace with your Kafka broker address if not running locally
KAFKA_TOPIC = 'transactions'

# Configure Kafka Producer
producer_config = {
    'bootstrap.servers': KAFKA_BROKER
}

producer = Producer(producer_config)

def produce_transaction(transaction_data):
    producer.produce(KAFKA_TOPIC, key=str(transaction_data['customer_id']), value=json.dumps(transaction_data).encode('utf-8'))
    producer.flush()
    print(f"Produced transaction: {transaction_data['customer_id']}")

print("Kafka Producer configured and 'produce_transaction' function defined.")

"""**Reasoning**:
With the Kafka producer set up, the next step is to configure a Kafka consumer to read messages from the `transactions` topic. This consumer will simulate receiving real-time transaction data that will then be processed by the fraud detection pipeline.


"""

# The Kafka consumer setup is commented out because a Kafka broker on 'localhost' is not directly accessible
# from within the Colab environment. We will simulate transaction consumption directly in the loop.
# from confluent_kafka import Consumer, KafkaException
# import uuid # Import uuid for generating unique IDs

# # Configure Kafka Consumer
# consumer_config = {
#     'bootstrap.servers': KAFKA_BROKER,
#     'group.id': f'fraud_detection_group_{uuid.uuid4()}', # Unique group ID
#     'auto.offset.reset': 'earliest'
# }

# # consumer = Consumer(consumer_config)
# # consumer.subscribe([KAFKA_TOPIC])

# # This function is no longer used for active Kafka consumption in this simulated setup.
# def consume_transaction():
#     return None

print("Kafka Consumer setup commented out. Consumption will be simulated via direct list iteration.")

"""## Produce Sample Transactions to Kafka

Let's simulate a stream of transactions by producing a few sample transactions to our `transactions` Kafka topic. These will then be consumed by our fraud detection pipeline.
"""

sample_transactions = [
    {
        "amount": 50,
        "location": "London",
        "device_id": "MOBILE_APP_123",
        "hour": 10,
        "customer_id": "CUST_1002"
    },
    {
        "amount": 1500,
        "location": "Russia",
        "device_id": "WEB_BROWSER_ABC",
        "hour": 3,
        "customer_id": "CUST_1003"
    },
    {
        "amount": 250,
        "location": "New York",
        "device_id": "POS_TERMINAL_XYZ",
        "hour": 14,
        "customer_id": "CUST_1004"
    },
    {
        "amount": 3000,
        "location": "Nigeria",
        "device_id": "VPN_DEVICE",
        "hour": 1,
        "customer_id": "CUST_1005"
    }
]

for tx in sample_transactions:
    produce_transaction(tx)
    time.sleep(1) # Simulate delay between transactions

print("Finished producing sample transactions to Kafka.")

"""## Modify Transaction Monitoring Agent to Consume from Kafka

Now, we'll modify the `transaction_monitoring_agent` so that instead of receiving the transaction as an argument, it first *consumes* a transaction from the Kafka topic. This simulates the agent listening for new events in real-time.
"""

# Agent 1: Transaction Monitoring Agent
# This agent acts as the entry point to the fraud detection pipeline.
# It logs the incoming transaction and passes it along to the next agents in the workflow.

def transaction_monitoring_agent(state: TransactionState) -> TransactionState:
    # state: TransactionState
    #   - The current shared state of the transaction. This agent receives the initial state.
    print("\n[Monitoring Agent]")
    print("Incoming Transaction:", state["transaction"])
    # It prints the transaction details for monitoring purposes.
    # In a real-world scenario, this agent might also perform initial data validation,
    # enrichment (e.g., fetching customer historical data), or logging to an audit system.
    return state
    # The agent returns the (unchanged) state, passing the transaction details to the next agent.

print("Transaction Monitoring Agent reverted to its original function.")

"""## Real-time Fraud Detection Loop

Finally, let's create a continuous loop that repeatedly calls the `fraud_pipeline`. Each iteration will attempt to consume a new transaction from Kafka, process it, and then display the results. This demonstrates a real-time fraud detection system.
"""

print("\nStarting simulated real-time fraud detection loop with enhanced agents...")

num_transactions_to_process = len(sample_transactions)
processed_count = 0
all_final_states = [] # New: List to store final states of all processed transactions

while processed_count < num_transactions_to_process:
    print(f"\n--- Processing Transaction {processed_count + 1} of {num_transactions_to_process} ---")

    # Simulate consuming a transaction by directly getting it from the sample_transactions list
    transaction_from_simulated_stream = sample_transactions[processed_count]

    # If a transaction is available, create an initial state with it and invoke the pipeline
    temp_initial_state = create_initial_state(transaction_from_simulated_stream)
    final_state = fraud_pipeline.invoke(temp_initial_state)

    # Check if the pipeline successfully processed the transaction
    if final_state and final_state.get("transaction") and final_state["transaction"] != {}:
        print("\n=========== FINAL RESULTS ==========")
        print(f"Transaction ID: {final_state['transaction'].get('customer_id')}")
        print("\nDecision:")
        print(final_state["final_decision"])
        print("\nSAR Report:")
        print(final_state["sar_report"])
        all_final_states.append(final_state) # New: Store the final state
        processed_count += 1 # Increment only upon successful processing
    else:
        # This case should ideally not happen with direct list access, but kept for robustness
        print("Pipeline run did not result in a valid processed transaction. Skipping.")

    time.sleep(1) # Simulate a short delay between processing transactions for demonstration

print("Simulated real-time fraud detection loop with enhanced agents finished.")

"""## Visualize Decision Outcomes

Now that we have processed all transactions and stored their final states, let's visualize the distribution of the `final_decision` outcomes (APPROVE, REVIEW, DECLINE).
"""

import pandas as pd
import matplotlib.pyplot as plt

# Extract decisions from all_final_states
decisions = []
for state in all_final_states:
    # The final_decision contains the full LLM response, extract just the DECISION part
    decision_text = state['final_decision']
    if "APPROVE" in decision_text:
        decisions.append("APPROVE")
    elif "REVIEW" in decision_text:
        decisions.append("REVIEW")
    elif "DECLINE" in decision_text:
        decisions.append("DECLINE")
    else:
        decisions.append("UNKNOWN") # Fallback for unexpected formats

# Create a pandas Series for easy counting
decision_counts = pd.Series(decisions).value_counts()

print("Decision Counts:")
print(decision_counts)

# Plot the decision counts
plt.figure(figsize=(8, 5))
decision_counts.plot(kind='bar', color=['skyblue', 'lightcoral', 'lightgreen'])
plt.title('Distribution of Fraud Detection Decisions')
plt.xlabel('Decision')
plt.ylabel('Number of Transactions')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Visualization of fraud detection decisions generated.")

"""## Implement a basic Streamlit dashboard

To visualize the results in a more interactive and user-friendly way, let's create a simple Streamlit dashboard for the 'Human Investigator Dashboard' component of your architecture.

First, we need to install the `streamlit` library.
"""

!pip install streamlit -q

"""Now, let's create a Streamlit application file (`app.py`). This script will use the `all_final_states` data collected from our simulated real-time loop to present the transaction details, decisions, and SAR reports in a dashboard format."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# # Assuming all_final_states is available globally or passed in another way
# # For simplicity in this Colab example, we'll try to access it if it's in the global scope.
# # In a real application, you'd likely load this data from a database, file, or real-time stream.
# 
# # Create a dummy all_final_states for local testing if not running in the Colab kernel where it's defined
# if 'all_final_states' not in st.session_state:
#     # This part is for running app.py directly outside the Colab environment after `%%writefile`
#     # In Colab, `all_final_states` will be in the global scope and passed via st.session_state below.
#     st.session_state.all_final_states = [
#         {
#             'transaction': {'amount': 100, 'location': 'USA', 'device_id': 'MOBILE', 'hour': 10, 'customer_id': 'CUST_001'},
#             'final_decision': '**DECISION: APPROVE**\nThis transaction is approved because all risk indicators are low.',
#             'sar_report': 'No SAR generated for approved transaction.'
#         },
#         {
#             'transaction': {'amount': 1500, 'location': 'Russia', 'device_id': 'VPN', 'hour': 2, 'customer_id': 'CUST_002'},
#             'final_decision': '**DECISION: DECLINE**\nHigh risk factors detected.',
#             'sar_report': 'SAR generated due to high risk indicators: location, device, and unusual hour.'
#         }
#     ]
# 
# # Transfer all_final_states from Colab's global scope to Streamlit's session state
# # This assumes `all_final_states` exists in the Colab execution environment.
# # If running the app.py directly, the dummy data above will be used.
# if 'all_final_states' in globals() and 'all_final_states_loaded' not in st.session_state:
#     st.session_state.all_final_states = globals()['all_final_states']
#     st.session_state.all_final_states_loaded = True
# 
# 
# st.set_page_config(layout="wide")
# 
# st.title("🕵️ Human Investigator Dashboard")
# st.markdown("--- ")
# 
# st.header("Processed Transactions Overview")
# 
# if not st.session_state.all_final_states:
#     st.info("No transactions have been processed yet.")
# else:
#     # Create a DataFrame for a quick overview
#     overview_data = []
#     for i, state in enumerate(st.session_state.all_final_states):
#         transaction = state.get('transaction', {})
#         decision = state.get('final_decision', 'N/A').split('**')[1].replace('DECISION: ','').strip() if '**DECISION:' in state.get('final_decision', 'N/A') else 'N/A'
#         overview_data.append({
#             'Transaction ID': transaction.get('customer_id', f'Txn {i+1}'),
#             'Amount': transaction.get('amount', 'N/A'),
#             'Location': transaction.get('location', 'N/A'),
#             'Decision': decision,
#             'Risk Score': state.get('risk_score', 'N/A'),
#             'ML Prob': round(state.get('ml_fraud_probability', 0.0), 2),
#             'AML Pattern': state.get('aml_pattern_detected', 'N/A'),
#             'Geo-Velocity': state.get('geo_velocity_risk', 'N/A'),
#             'Synthetic ID': state.get('synthetic_identity_flag', 'N/A')
#         })
#     df_overview = pd.DataFrame(overview_data)
#     st.dataframe(df_overview, use_container_width=True)
# 
#     st.markdown("--- ")
#     st.header("Detailed Transaction Analysis")
# 
#     for i, state in enumerate(st.session_state.all_final_states):
#         transaction = state.get('transaction', {})
#         final_decision = state.get('final_decision', 'N/A')
#         sar_report = state.get('sar_report', 'N/A')
# 
#         st.subheader(f"Transaction {i+1}: ID {transaction.get('customer_id', 'N/A')}")
# 
#         col1, col2, col3 = st.columns(3)
#         with col1:
#             st.metric("Risk Score", state.get('risk_score', 'N/A'))
#             st.metric("Rule-Based Flag", str(state.get('rule_based_flag', 'N/A')))
#             st.metric("Geo Risk", state.get('geo_risk', 'N/A'))
#         with col2:
#             st.metric("ML Fraud Probability", round(state.get('ml_fraud_probability', 0.0), 2))
#             st.metric("Device Risk", state.get('device_risk', 'N/A'))
#             st.metric("Behavior Risk", state.get('behavior_risk', 'N/A'))
#         with col3:
#             st.metric("AML Pattern", state.get('aml_pattern_detected', 'N/A'))
#             st.metric("Behavioral Biometrics", state.get('behavioral_biometrics_risk', 'N/A'))
#             st.metric("Geo-Velocity Risk", state.get('geo_velocity_risk', 'N/A'))
#             st.metric("Synthetic Identity", str(state.get('synthetic_identity_flag', 'N/A')))
#             st.metric("Account Takeover Risk", state.get('account_takeover_risk', 'N/A'))
# 
#         with st.expander("Transaction Details"):
#             st.json(transaction)
# 
#         st.markdown(f"**Final Decision:**")
#         st.markdown(final_decision)
# 
#         if "SAR Generated" in sar_report or "Suspicious Activity Report" in sar_report:
#             st.markdown(f"**Suspicious Activity Report:**")
#             st.markdown(sar_report)
#         else:
#             st.info("No detailed SAR report generated for this transaction.")
#         st.markdown("--- ")

"""Now that the `app.py` file is created, you can run the Streamlit dashboard by executing the following command in a new code cell.

Since Colab Notebooks are typically remote environments, Streamlit applications need to be exposed via `ngrok` or `localtunnel` to be accessible in your browser. I will use `localtunnel` for this.

First, install `localtunnel`:

```bash
!npm install -g localtunnel
```

Then, run the Streamlit app and expose it:

```bash
!streamlit run app.py &>/dev/null& npx localtunnel --port 8501
```

After executing the command, a URL will be provided (usually ending in `.loca.lt`) which you can open in your browser to view the dashboard.
"""

!npm install -g localtunnel

!streamlit run app.py &>/dev/null& npx localtunnel --port 8501